version: '3.7'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-power-search
    volumes:
      - mysql-power-search-db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: abc
      MYSQL_PASSWORD: def
      MYSQL_DATABASE: power_search_db
    ports:
      - '3307:3306'

volumes:
  mysql-power-search-db: